### ISSUE TITLE
Unhandled Promise rejection by Zone.js Error in Angular7

### ISSUE THREAD

**Issue by jaykhatriwebdesigner** [infusion-code/angular-maps#113]
Error:
Unhandled Promise rejection: Cannot redefine property: prototype ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot redefine property: prototype
    at defineProperty (<anonymous>)
    at _tryDefineProperty (zone-evergreen.js:2230)
    at Function.Object.defineProperty (zone-evergreen.js:2180)
    at Extender.Set (angular-maps.js:2784)
    at Extender.Extend (angular-maps.js:2763)
    at MixinMapLabelWithOverlayView$1 (angular-maps.js:5008)
    at angular-maps.js:14557
    at ZoneDelegate.invoke (zone-evergreen.js:359)
    at Zone.run (zone-evergreen.js:124)
    at zone-evergreen.js:855 TypeError: Cannot redefine property: prototype
    at defineProperty (<anonymous>)
    at _tryDefineProperty (http://localhost:4200/polyfills.js:8308:16)
    at Function.Object.defineProperty (http://localhost:4200/polyfills.js:8258:16)
    at Extender.Set (http://localhost:4200/vendor.js:165005:16)
    at Extender.Extend (http://localhost:4200/vendor.js:164984:14)
    at MixinMapLabelWithOverlayView$1 (http://localhost:4200/vendor.js:167229:10)
    at http://localhost:4200/vendor.js:176778:13
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.js:6437:26)
    at Zone.run (http://localhost:4200/polyfills.js:6202:43)
    at http://localhost:4200/polyfills.js:6933:36

Here is my package which i am using 

{
  "name": "frontend",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.7",
    "@angular/cdk": "~8.2.3",
    "@angular/common": "~8.2.7",
    "@angular/compiler": "~8.2.7",
    "@angular/core": "~8.2.7",
    "@angular/forms": "~8.2.7",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.2.7",
    "@angular/platform-browser-dynamic": "~8.2.7",
    "@angular/router": "~8.2.7",
    "@ng-bootstrap/ng-bootstrap": "^5.1.1",
    "core-js": "2.5.5",
    "zone.js": "~0.9.1",
    "bingmaps": "2.0.3",
    "angular-maps": "^6.0.3",
    "hammerjs": "^2.0.8",
    "jquery": "^3.4.1",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.5",
    "@angular/cli": "~8.3.5",
    "@angular/compiler-cli": "~8.2.7",
    "@angular/language-service": "~8.2.7",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}

**Comment by thor-schueler** [comment]
Seems related to #110
